channels:
  - defaults
dependencies:
  - pip:
      - beautifulsoup4=4.12
      - pandas==2.2.2
      - pystac==1.11.0
      - pystac-client==0.8.5
      - rasterio==1.3.10
      - requests=2.31
      - rio-stac=0.8
      - shapely=2.0