channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - pip:
      - beautifulsoup4
      - pandas
      - pystac==1.11.0
      - pystac-client==0.8.5
      - rasterio==1.5
      - requests
      - rio-stac==0.12
      - shapely